work_dir: ./work_dir/skeleton-mixformer/train_j

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/train_joint.npy
  label_path: ./data/train_label.npy
  split: train
  debug: False
  random_choose: False
  random_shift: True
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: ./data/val_joint.npy
  label_path: ./data/val_label.npy
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ske_mixf.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav_mixf.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 0.2
step: [50]
warm_up_epoch: 5

# training
device: 0
batch_size: 64
test_batch_size: 64
num_epoch: 70
nesterov: True
