work_dir: ./work_dir/train/tdgcn_b

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/train_joint.npy
  label_path: ./data/train_label.npy
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: ./data/val_joint.npy
  label_path: ./data/val_label.npy
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False

# model
model: model.tdgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 65
nesterov: True
